source 'https://rubygems.org'

# Project requirements
gem 'rake'

# Component requirements
gem 'bcrypt'
gem 'erubis', '~> 2.7.0'
gem 'activerecord', '>= 3.1', :require => 'active_record'
gem 'sqlite3'
gem 'rest-client'
gem 'sucker_punch', '~> 1.0'
# Test requirements

# Padrino Stable Gem
gem 'padrino', '0.13.0'
gem 'memcached'
